import { DriverPartner, ServiceZone, Trip, VehicleConfig, LocationPoint } from '@/types/logistics';

export const BANGALORE_LANDMARKS: LocationPoint[] = [
  {
    address: "MG Road Metro Station, Shivaji Nagar",
    area: "Central Bangalore",
    lat: 12.9756,
    lng: 77.6066,
    landmark: "Near Brigade Road Junction",
  },
  {
    address: "100 Feet Road, Indiranagar 12th Main",
    area: "Indiranagar",
    lat: 12.9784,
    lng: 77.6408,
    landmark: "Opposite Toit Brewpub",
  },
  {
    address: "Sony World Signal, 80 Feet Road, 4th Block",
    area: "Koramangala",
    lat: 12.9345,
    lng: 77.6265,
    landmark: "Koramangala Commercial Hub",
  },
  {
    address: "27th Main Road, Sector 1, HSR Layout",
    area: "HSR Layout",
    lat: 12.9116,
    lng: 77.6389,
    landmark: "Near NIFT Campus",
  },
  {
    address: "ITPL Main Road, Pattandur Agrahara",
    area: "Whitefield",
    lat: 12.9854,
    lng: 77.7289,
    landmark: "Near International Tech Park",
  },
  {
    address: "Ecospace Business Park, Outer Ring Road",
    area: "Bellandur",
    lat: 12.9260,
    lng: 77.6835,
    landmark: "Near Devarabisanahalli Flyover",
  },
  {
    address: "4th Block Complex, 11th Main Road",
    area: "Jayanagar",
    lat: 12.9299,
    lng: 77.5826,
    landmark: "Near Jayanagar BDA Complex",
  },
  {
    address: "Phase 1 Toll Gate, Hosur Road",
    area: "Electronic City",
    lat: 12.8452,
    lng: 77.6602,
    landmark: "Near Infosys Gate 1",
  },
  {
    address: "Peenya 2nd Stage, Industrial Estate",
    area: "Peenya Industrial Area",
    lat: 13.0334,
    lng: 77.5147,
    landmark: "Near Peenya Metro Depot",
  },
];

export const VEHICLE_CONFIGS: VehicleConfig[] = [
  {
    id: '2wheeler',
    name: '2-Wheeler (Bike)',
    tagline: 'Ideal for courier, documents & parcels up to 20kg',
    capacityKg: 20,
    dimensions: '40 x 40 x 40 cm',
    icon: 'Bike',
    baseFare: 45,
    baseKm: 2,
    perKmRate: 9,
    waitingChargePerMin: 1.5,
    helperFee: 0,
    surgeMultiplier: 1.0,
  },
  {
    id: '3wheeler',
    name: '3-Wheeler (Cargo Auto)',
    tagline: 'Best for boxes, small appliances & retail goods',
    capacityKg: 500,
    dimensions: '5 x 4 x 4 ft',
    icon: 'CarFront',
    baseFare: 140,
    baseKm: 3,
    perKmRate: 16,
    waitingChargePerMin: 2.5,
    helperFee: 150,
    surgeMultiplier: 1.0,
  },
  {
    id: 'tata_ace',
    name: 'Tata Ace (Chota Hathi)',
    tagline: 'Bangalore favorite for house shifting & commercial freight',
    capacityKg: 1000,
    dimensions: '7 x 4.5 x 5 ft',
    icon: 'Truck',
    baseFare: 280,
    baseKm: 3,
    perKmRate: 24,
    waitingChargePerMin: 3.5,
    helperFee: 250,
    surgeMultiplier: 1.1,
  },
  {
    id: 'pickup_8ft',
    name: '8ft Large Pickup (Bolero)',
    tagline: 'Heavy machinery, large furniture, event equipment',
    capacityKg: 1700,
    dimensions: '8 x 5 x 5.5 ft',
    icon: 'Container',
    baseFare: 480,
    baseKm: 4,
    perKmRate: 34,
    waitingChargePerMin: 4.5,
    helperFee: 350,
    surgeMultiplier: 1.15,
  },
];

export const SERVICE_ZONES: ServiceZone[] = [
  {
    id: 'zone_blr_central',
    name: 'Central Bengaluru Zone',
    city: 'Bengaluru',
    center: { lat: 12.9716, lng: 77.5946 },
    radiusKm: 7,
    isActive: true,
    surgeMultiplier: 1.15,
    pincodes: ['560001', '560025', '560042', '560038'],
  },
  {
    id: 'zone_blr_south',
    name: 'South Bengaluru & Tech Corridor',
    city: 'Bengaluru',
    center: { lat: 12.9141, lng: 77.6211 },
    radiusKm: 12,
    isActive: true,
    surgeMultiplier: 1.25,
    pincodes: ['560034', '560095', '560100', '560068', '560078'],
  },
  {
    id: 'zone_blr_east',
    name: 'East Bengaluru & ITPL Tech Hub',
    city: 'Bengaluru',
    center: { lat: 12.9698, lng: 77.7500 },
    radiusKm: 10,
    isActive: true,
    surgeMultiplier: 1.1,
    pincodes: ['560066', '560037', '560048', '560087'],
  },
  {
    id: 'zone_blr_north',
    name: 'North Bengaluru Airport Expressway',
    city: 'Bengaluru',
    center: { lat: 13.0358, lng: 77.5970 },
    radiusKm: 14,
    isActive: true,
    surgeMultiplier: 1.0,
    pincodes: ['560024', '560045', '560092', '560064'],
  },
  {
    id: 'zone_blr_west',
    name: 'West Bengaluru & Peenya Industrial',
    city: 'Bengaluru',
    center: { lat: 13.0100, lng: 77.5250 },
    radiusKm: 11,
    isActive: true,
    surgeMultiplier: 1.0,
    pincodes: ['560010', '560058', '560079', '560086'],
  },
];

export const INITIAL_DRIVERS: DriverPartner[] = [
  {
    id: 'drv_01',
    name: 'Ramesh Gowda',
    phone: '+91 98450 12345',
    email: 'ramesh.gowda@swifload.test',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    vehicleCategory: 'tata_ace',
    vehicleModel: 'Tata Ace Gold Diesel (White)',
    vehicleNumber: 'KA-05-MJ-4412',
    isOnline: true,
    currentStatus: 'IDLE',
    currentLocation: { lat: 12.9360, lng: 77.6240 }, // Koramangala
    rating: 4.89,
    totalTrips: 418,
    acceptanceRate: 96,
    kycStatus: 'VERIFIED',
    kycDocuments: [
      { docType: 'DRIVING_LICENSE', docNumber: 'KA0520190012345', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Commercial+Driving+License', verified: true },
      { docType: 'RC_BOOK', docNumber: 'KA05MJ4412', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Vehicle+RC+Smartcard', verified: true },
      { docType: 'VEHICLE_INSURANCE', docNumber: 'POL-ICICI-882194', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Comprehensive+Insurance', verified: true },
      { docType: 'AADHAAR', docNumber: 'XXXX-XXXX-8921', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=UIDAI+Aadhaar+Front+Back', verified: true }
    ],
    bankDetails: {
      accountName: 'Ramesh Kumar Gowda',
      accountNumber: '50100234918231',
      ifscCode: 'HDFC0000240',
      upiId: 'rameshgowda@oksbi',
    },
    wallet: {
      balance: 3450,
      todayEarnings: 1680,
      pendingPayout: 1200,
    }
  },
  {
    id: 'drv_02',
    name: 'Syed Imran',
    phone: '+91 97412 88765',
    email: 'imran.syed@swifload.test',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    vehicleCategory: '3wheeler',
    vehicleModel: 'Piaggio Ape Extra LDX',
    vehicleNumber: 'KA-01-EQ-9081',
    isOnline: true,
    currentStatus: 'IDLE',
    currentLocation: { lat: 12.9770, lng: 77.6390 }, // Indiranagar
    rating: 4.82,
    totalTrips: 620,
    acceptanceRate: 94,
    kycStatus: 'VERIFIED',
    kycDocuments: [
      { docType: 'DRIVING_LICENSE', docNumber: 'KA0120180098471', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Commercial+DL', verified: true },
      { docType: 'RC_BOOK', docNumber: 'KA01EQ9081', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Vehicle+RC', verified: true },
      { docType: 'VEHICLE_INSURANCE', docNumber: 'BAJAJ-ALL-4421', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Insurance+Valid', verified: true },
      { docType: 'AADHAAR', docNumber: 'XXXX-XXXX-3341', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Aadhaar+Card', verified: true }
    ],
    bankDetails: {
      accountName: 'Syed Imran',
      accountNumber: '918739120934',
      ifscCode: 'SBIN0004121',
      upiId: 'syedimran@paytm',
    },
    wallet: {
      balance: 1890,
      todayEarnings: 820,
      pendingPayout: 650,
    }
  },
  {
    id: 'drv_03',
    name: 'Kiran Kumar Reddy',
    phone: '+91 99001 54321',
    email: 'kiran.reddy@swifload.test',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    vehicleCategory: '2wheeler',
    vehicleModel: 'Hero Splendor Plus (Delivery Rack)',
    vehicleNumber: 'KA-04-HX-2198',
    isOnline: true,
    currentStatus: 'IDLE',
    currentLocation: { lat: 12.9130, lng: 77.6350 }, // HSR Layout
    rating: 4.95,
    totalTrips: 1240,
    acceptanceRate: 98,
    kycStatus: 'VERIFIED',
    kycDocuments: [
      { docType: 'DRIVING_LICENSE', docNumber: 'KA0420200084321', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=2W+DL', verified: true },
      { docType: 'RC_BOOK', docNumber: 'KA04HX2198', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Bike+RC', verified: true },
      { docType: 'VEHICLE_INSURANCE', docNumber: 'GO-DIGIT-9921', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Digit+Insurance', verified: true },
      { docType: 'AADHAAR', docNumber: 'XXXX-XXXX-6112', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Aadhaar+KYC', verified: true }
    ],
    bankDetails: {
      accountName: 'Kiran Reddy',
      accountNumber: '60199201948',
      ifscCode: 'CNRB0001923',
      upiId: 'kiranreddy@ybl',
    },
    wallet: {
      balance: 2420,
      todayEarnings: 940,
      pendingPayout: 800,
    }
  },
  {
    id: 'drv_04',
    name: 'Manjunath Swamy',
    phone: '+91 96118 73210',
    email: 'manjunath.s@swifload.test',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    vehicleCategory: 'pickup_8ft',
    vehicleModel: 'Mahindra Bolero Maxi Truck Plus',
    vehicleNumber: 'KA-51-B-6721',
    isOnline: false,
    currentStatus: 'OFFLINE',
    currentLocation: { lat: 12.9830, lng: 77.7250 }, // Whitefield
    rating: 4.78,
    totalTrips: 310,
    acceptanceRate: 91,
    kycStatus: 'VERIFIED',
    kycDocuments: [
      { docType: 'DRIVING_LICENSE', docNumber: 'KA5120170041234', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Heavy+Commercial+DL', verified: true },
      { docType: 'RC_BOOK', docNumber: 'KA51B6721', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Bolero+RC', verified: true },
      { docType: 'VEHICLE_INSURANCE', docNumber: 'ROYAL-SUNDARAM-1049', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Commercial+Insurance', verified: true },
      { docType: 'AADHAAR', docNumber: 'XXXX-XXXX-1994', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Aadhaar+Card', verified: true }
    ],
    bankDetails: {
      accountName: 'Manjunatha Swamy',
      accountNumber: '110294820194',
      ifscCode: 'KARB0000102',
      upiId: 'manju.swamy@axl',
    },
    wallet: {
      balance: 5120,
      todayEarnings: 0,
      pendingPayout: 3200,
    }
  },
  {
    id: 'drv_05',
    name: 'Anand Kumar V',
    phone: '+91 91081 22938',
    email: 'anand.kv@swifload.test',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    vehicleCategory: 'tata_ace',
    vehicleModel: 'Tata Ace EV (Electric 1-Ton)',
    vehicleNumber: 'KA-03-NA-1844',
    isOnline: false,
    currentStatus: 'OFFLINE',
    currentLocation: { lat: 13.0300, lng: 77.5180 }, // Peenya
    rating: 0,
    totalTrips: 0,
    acceptanceRate: 100,
    kycStatus: 'PENDING',
    kycDocuments: [
      { docType: 'DRIVING_LICENSE', docNumber: 'KA0320230099881', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Driving+License+Under+Review', verified: false },
      { docType: 'RC_BOOK', docNumber: 'KA03NA1844', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Tata+Ace+EV+RC+Review', verified: false },
      { docType: 'VEHICLE_INSURANCE', docNumber: 'ICICI-LOMB-7741', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Insurance+Copy', verified: false },
      { docType: 'AADHAAR', docNumber: 'XXXX-XXXX-9023', fileUrl: 'https://placehold.co/600x400/1e293b/ffffff?text=Aadhaar+Card', verified: false }
    ],
    bankDetails: {
      accountName: 'Anand Kumar V',
      accountNumber: '0024104000192834',
      ifscCode: 'IBKL0000024',
      upiId: 'anandkv@icici',
    },
    wallet: {
      balance: 0,
      todayEarnings: 0,
      pendingPayout: 0,
    }
  }
];

export const INITIAL_TRIPS: Trip[] = [
  {
    id: 'trip_blr_1001',
    bookingCode: 'SWF-8921',
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    customerId: 'cust_01',
    customerName: 'Priya Sharma',
    customerPhone: '+91 98801 99234',
    vehicleCategory: 'tata_ace',
    pickup: {
      address: 'Sony World Signal, 80 Feet Road, 4th Block',
      area: 'Koramangala',
      lat: 12.9345,
      lng: 77.6265,
      landmark: 'Near Starbucks Koramangala',
      senderOrReceiverName: 'Priya (Sender)',
      contactPhone: '+91 98801 99234',
    },
    drop: {
      address: '100 Feet Road, Indiranagar 12th Main',
      area: 'Indiranagar',
      lat: 12.9784,
      lng: 77.6408,
      landmark: 'Opposite Toit Brewpub, 2nd Floor',
      senderOrReceiverName: 'Vikram Mehta (Receiver)',
      contactPhone: '+91 98450 88712',
    },
    distanceKm: 6.8,
    durationMins: 28,
    shipment: {
      goodsCategory: 'Furniture & Home Decor',
      approxWeightKg: 180,
      packageCount: 4,
      hasHelperRequired: true,
      notes: 'Contains a glass dining table top and wooden chairs. Please handle gently.',
      pickupOtp: '4821',
      deliveryOtp: '7392',
      cargoPhotoUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&auto=format&fit=crop&q=80',
    },
    fare: {
      baseFare: 280,
      distanceFare: 91,
      waitingFare: 0,
      helperFee: 250,
      surgeFare: 35,
      taxGst: 32.8,
      totalFare: 688.8,
      platformCommission: 120,
      driverEarnings: 568.8,
    },
    paymentMethod: 'UPI_GPAY',
    paymentStatus: 'PAID',
    status: 'IN_TRANSIT',
    driverId: 'drv_01',
    driverName: 'Ramesh Gowda',
    driverPhone: '+91 98450 12345',
    driverVehicleNumber: 'KA-05-MJ-4412',
    driverRating: 4.89,
    driverLocation: { lat: 12.9560, lng: 77.6330 },
    auditHistory: [
      { timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(), event: 'Trip booked by Priya Sharma', actor: 'Customer' },
      { timestamp: new Date(Date.now() - 23 * 60 * 1000).toISOString(), event: 'Driver Ramesh Gowda auto-allocated', actor: 'System' },
      { timestamp: new Date(Date.now() - 21 * 60 * 1000).toISOString(), event: 'Driver accepted trip offer', actor: 'Driver' },
      { timestamp: new Date(Date.now() - 14 * 60 * 1000).toISOString(), event: 'Driver arrived at Koramangala pickup', actor: 'Driver' },
      { timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString(), event: 'Goods loaded. Pickup OTP 4821 verified', actor: 'Driver' },
    ],
  },
  {
    id: 'trip_blr_1002',
    bookingCode: 'SWF-8919',
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    customerId: 'cust_02',
    customerName: 'Aditya Verma (CloudKitchens)',
    customerPhone: '+91 97312 44102',
    vehicleCategory: '2wheeler',
    pickup: {
      address: '27th Main Road, Sector 1, HSR Layout',
      area: 'HSR Layout',
      lat: 12.9116,
      lng: 77.6389,
      landmark: 'Near NIFT Campus',
      senderOrReceiverName: 'CloudKitchen Hub',
      contactPhone: '+91 97312 44102',
    },
    drop: {
      address: 'Ecospace Business Park, Outer Ring Road',
      area: 'Bellandur',
      lat: 12.9260,
      lng: 77.6835,
      landmark: 'Tower 2 Reception',
      senderOrReceiverName: 'Corporate Pantry Desk',
      contactPhone: '+91 98450 11928',
    },
    distanceKm: 5.4,
    durationMins: 20,
    shipment: {
      goodsCategory: 'Groceries & Perishables',
      approxWeightKg: 12,
      packageCount: 2,
      hasHelperRequired: false,
      notes: 'Bakery hampers in thermo box. Keep upright.',
      pickupOtp: '1109',
      deliveryOtp: '8820',
      proofOfDeliveryPhoto: 'https://placehold.co/600x400/10b981/ffffff?text=Delivery+Proof+Handover+Confirmed',
    },
    fare: {
      baseFare: 45,
      distanceFare: 30.6,
      waitingFare: 0,
      helperFee: 0,
      surgeFare: 0,
      taxGst: 3.8,
      totalFare: 79.4,
      platformCommission: 15,
      driverEarnings: 64.4,
    },
    paymentMethod: 'NETBANKING_IMPS',
    paymentStatus: 'PAID',
    status: 'DELIVERED',
    driverId: 'drv_03',
    driverName: 'Kiran Kumar Reddy',
    driverPhone: '+91 99001 54321',
    driverVehicleNumber: 'KA-04-HX-2198',
    driverRating: 4.95,
    customerRating: 5,
    customerFeedback: 'Super fast delivery in peak Bellandur traffic!',
    auditHistory: [
      { timestamp: new Date(Date.now() - 3 * 3600 * 1000).toISOString(), event: 'Trip booked', actor: 'Customer' },
      { timestamp: new Date(Date.now() - 2.8 * 3600 * 1000).toISOString(), event: 'Assigned to Kiran Reddy', actor: 'System' },
      { timestamp: new Date(Date.now() - 2.4 * 3600 * 1000).toISOString(), event: 'Delivered successfully with OTP 8820', actor: 'Driver' },
    ],
  },
  {
    id: 'trip_blr_1003',
    bookingCode: 'SWF-8910',
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    customerId: 'cust_03',
    customerName: 'Deepak Electricals',
    customerPhone: '+91 94480 33190',
    vehicleCategory: '3wheeler',
    pickup: {
      address: 'Peenya 2nd Stage, Industrial Estate',
      area: 'Peenya Industrial Area',
      lat: 13.0334,
      lng: 77.5147,
      landmark: 'Near Peenya Metro Depot',
    },
    drop: {
      address: 'MG Road Metro Station, Shivaji Nagar',
      area: 'Central Bangalore',
      lat: 12.9756,
      lng: 77.6066,
      landmark: 'Near Brigade Road Junction',
    },
    distanceKm: 14.2,
    durationMins: 45,
    shipment: {
      goodsCategory: 'Hardware & Building Materials',
      approxWeightKg: 320,
      hasHelperRequired: false,
      pickupOtp: '3391',
      deliveryOtp: '9012',
    },
    fare: {
      baseFare: 140,
      distanceFare: 179.2,
      waitingFare: 0,
      helperFee: 0,
      surgeFare: 0,
      taxGst: 16.0,
      totalFare: 335.2,
      platformCommission: 65,
      driverEarnings: 270.2,
    },
    paymentMethod: 'CASH_ON_DELIVERY',
    paymentStatus: 'PAID',
    status: 'DELIVERED',
    driverId: 'drv_02',
    driverName: 'Syed Imran',
    driverPhone: '+91 97412 88765',
    driverVehicleNumber: 'KA-01-EQ-9081',
    driverRating: 4.82,
    customerRating: 5,
    customerFeedback: 'Very professional driver. Goods delivered intact.',
    auditHistory: [
      { timestamp: new Date(Date.now() - 5 * 3600 * 1000).toISOString(), event: 'Trip booked', actor: 'Customer' },
      { timestamp: new Date(Date.now() - 4.1 * 3600 * 1000).toISOString(), event: 'Delivered & Cash Collected ₹335', actor: 'Driver' },
    ],
  },
];
